# Generated by Django 6.0.6 on 2026-06-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jm_cd', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('qualification_cl', models.CharField(blank=True, max_length=50)),
                ('series_name', models.CharField(blank=True, max_length=100)),
                ('major_job_field', models.CharField(blank=True, max_length=100)),
                ('minor_job_field', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
