# Generated by Django 5.2.15 on 2026-06-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jm_cd', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('qualification_cl', models.CharField(blank=True, max_length=50)),
                ('series_name', models.CharField(blank=True, max_length=100)),
                ('major_job_field', models.CharField(blank=True, max_length=100)),
                ('minor_job_field', models.CharField(blank=True, max_length=100)),
                ('ai_fit_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jm_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=200)),
                ('doc_reg_start', models.DateField(blank=True, null=True)),
                ('doc_reg_end', models.DateField(blank=True, null=True)),
                ('doc_exam_start', models.DateField(blank=True, null=True)),
                ('doc_exam_end', models.DateField(blank=True, null=True)),
                ('doc_pass_dt', models.DateField(blank=True, null=True)),
                ('doc_submit_start', models.DateField(blank=True, null=True)),
                ('doc_submit_end', models.DateField(blank=True, null=True)),
                ('prac_reg_start', models.DateField(blank=True, null=True)),
                ('prac_reg_end', models.DateField(blank=True, null=True)),
                ('prac_exam_start', models.DateField(blank=True, null=True)),
                ('prac_exam_end', models.DateField(blank=True, null=True)),
                ('prac_pass_start', models.DateField(blank=True, null=True)),
                ('prac_pass_end', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='certifications.certification', to_field='jm_cd')),
            ],
            options={
                'unique_together': {('certification', 'plan_name')},
            },
        ),
    ]
