# Generated by Django 5.2.15 on 2026-06-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='ai_score',
        ),
    ]
