# Generated by Django 5.2.15 on 2026-06-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='ai_score',
            new_name='ai_fit_score',
        ),
    ]
