# Generated by Django 5.2.15 on 2026-06-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('certifications', '0002_rename_ai_score_certification_ai_fit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='category.category'),
        ),
        migrations.AddField(
            model_name='certification',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='category.label'),
        ),
    ]
