# Generated by Django 5.2.15 on 2026-06-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_name'),
        ('jobs', '0002_rename_personnel_recruitment_recruitment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_process', models.CharField(blank=True, max_length=100, null=True)),
                ('expense', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_time', models.CharField(blank=True, max_length=100, null=True)),
                ('recruitment_linkage', models.CharField(blank=True, max_length=100, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('close_date_text', models.CharField(blank=True, max_length=100, null=True)),
                ('recruitment_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootcamps', to='category.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootcamps', to='jobs.company')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootcamps.region')),
                ('skills', models.ManyToManyField(blank=True, related_name='bootcamps', to='bootcamps.skill')),
            ],
        ),
    ]
