# Generated by Django 5.2.15 on 2026-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='close_date_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='expense',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='participation_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='program_process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='recruitment_linkage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
