# Generated by Django 5.2.15 on 2026-06-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
        ('category', '0004_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='category.label'),
        ),
    ]
