# Generated by Django 5.2.15 on 2026-06-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('annual_sales', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('career', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('working_type', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_count', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_url', models.URLField(unique=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('wanted_auth_no', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='category.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='jobs.company')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to='category.label')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('preferred_qualification', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('computer_skill', models.TextField(blank=True, null=True)),
                ('foreign_language', models.TextField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('break_time', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('social_insurance', models.TextField(blank=True, null=True)),
                ('retirement_pay', models.TextField(blank=True, null=True)),
                ('submission_documents', models.TextField(blank=True, null=True)),
                ('application_method', models.TextField(blank=True, null=True)),
                ('recruitment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='jobs.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='jobs.recruitment')),
            ],
            options={
                'unique_together': {('recruitment', 'name')},
            },
        ),
    ]
