# Generated by Django 5.2.4 on 2026-06-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
