# Generated by Django 5.2.4 on 2026-06-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='personnel',
            new_name='recruitment_count',
        ),
        migrations.RenameField(
            model_name='recruitment',
            old_name='industry_type',
            new_name='working_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='ai_recommend_score',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='basic_address',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='jobs_code',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='personal_history',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='company',
            name='annual_sales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='wanted_auth_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='category.category'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='jobs.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('preferred_qualification', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('computer_skill', models.TextField(blank=True, null=True)),
                ('foreign_language', models.TextField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('break_time', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('social_insurance', models.TextField(blank=True, null=True)),
                ('retirement_pay', models.TextField(blank=True, null=True)),
                ('submission_documents', models.TextField(blank=True, null=True)),
                ('application_method', models.TextField(blank=True, null=True)),
                ('ai_fit_score', models.IntegerField(blank=True, null=True)),
                ('recruitment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='jobs.recruitment')),
            ],
        ),
    ]
