# Generated by Django 5.2.4 on 2026-06-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_name_alter_recruitment_recruitment_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hiringprocess',
            unique_together={('recruitment', 'name')},
        ),
    ]
