# Generated by Django 5.2.15 on 2026-06-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('bootcamp', '부트캠프'), ('job', '채용공고'), ('certification', '자격증'), ('competition', '공모전')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'score'], name='ai_score_fi_user_id_be872b_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
