# Generated by Django 6.0.6 on 2026-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('homepage', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('detail_url', models.URLField(blank=True)),
                ('description', models.JSONField(default=dict)),
            ],
        ),
    ]
