# Generated by Django 6.0.6 on 2026-06-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='status',
        ),
    ]
