# Generated by Django 5.2.15 on 2026-06-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('competitions', '0002_remove_competition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ai_fit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='category.label'),
        ),
    ]
